### ISSUE TITLE
Unstable job status is not displayed

### ISSUE THREAD

**Issue by nfalco79** [rackerlabs/canon-jenkins#13]
The unstable build color status is not displayed after build was run or running.
Seems missing style for 
```css
/* Unstable state (yellow) styling for project table */
#projectstatus td:first-child[data="2"] {
    background-color: #FFA400 !important;
}

...
/* Building state (orange stripes) styling for main project table and build process table on left side */
#projectstatus td:first-child[data="1"],
#projectstatus td:first-child[data="3"], <-- missing this
...
```
