### ISSUE TITLE
Progress bar of stable build display wrong animation

### ISSUE THREAD

**Issue by nfalco79** [rackerlabs/canon-jenkins#14]
Progress bar for stable build are display with yellow progress instead of green progress bar
```css
/* Building state (green stripes) styling for main project table and build process table on left side */
#projectstatus td:first-child[data="5"] {
    background-image: url("data:image/png;base64,R0lGODlhGgAaAMQAAH7Vt2zPq2rNq2bNqWjNqSC1gR6zfhyzfhizfByzfBqzfBixehaxehKxeBSxeBCvdg6vdgKrbgCpbP4BAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQFBQATACwAAAAAGgAaAAAF0+AAjEDwRFIaISJpoipCAoMBS9HSjvWd74KFz0CYBYdFnjCFewhmg6XKSRochgHolRkxZEcCh09nFHPJJNv5SSKoVQv2iOA77ADh+j3MddwHCj5+UIEqBnJ4CUOIAooqDklzZo+RAASTEQqMbziaRpwJf5M4oVCjEYhWgqlbj1pIr1xEVQyrULV9cgIFeka8XHYkAifAe8QqwXOcEQx3bj7NM1I4BX/TEdVQPlRVCNupCLKpy4dQbzmVBA1j6esxzr/vMwTxXX/uhvc3DX/L/OY+QgAAIfkEBQUAEwAsAAAAABoAGgAABc8gMkwkEDwkGYmpiabRWA4GHC3yBND20go+mIHwC6qGM+Mk8hC0BkqmUzc42AyBp1WY1QkcvRzgG04RarDFVHfurQFg2EFMltNtDvFAgdfzj28CCVeBgyoORCUEcYeJbIwRCoFoKpI/lBEJepCZmzAOb1V4oVsqjjulS0gzqRGUOwyjT7GfU2MFNnM/uHYlAi8qur7AS8IAbTAMYsgqyilQNgV6UdItCDZNT9cw2TOET5iuoZgLpwQNPeboKiyKvOzL765660f0MA164fngMCEAIfkEBQUAEwAsAAAAABoAGgAABdBghAxTCQRPWYqkiarT0k7AYMCRrNa3GhE7wQJnAJqExN1g6HsIlMyV0zQ4EANKq8+ApQkcON0R7BMDCL3V4mlCh9mTL+4wA8h99J0C56gP9j59SkRwdgmEQYcrDkY0BGSLjWeQEQqFAmkTlZdpEQl+lJ6ggYVVfKVaJUVZRJKmPqUMp0qygUEFc3UCuHgtdim9QcAreY6ZEQx1bj7JVFGaBX7PEdEqAwg4U1TYTYXHBqXfpWGSBA3kO+Y+I+m8K+xt7hEGfudb9T4Nfsf6SmkhACH5BAUFABMALAAAAAAaABoAAAXTYBQhA2ACwSOJInmiKruU52CsMm3aeGQQL8Gi5wOehETBazBkRR7KWpP1WB6IhoAVqzUJHMRZEOwUmwi3cvSclq2/xIMOAHfKawqiYz7IO/cvCVhrdIJOBoQCekZnZCwOjAAEDk4KiW0ilkGYCXyOIp1Lnw6EA1d/paciP1uHkaY9pEsMeqW0TnMCBXG5u3ZBMSx3R8Eiw5KYEQxzaETLUkQFfFMi0jUIRFBL2E7aO8mIS+CEDWGRBOVl50QuJwS+LO1nBYd86SwG9j0NfMn84itCAAAh+QQFBQATACwAAAAAGgAaAAAFzGAkIgNgAsEjruSJqutSnoOxirJb3wbhCotbpPcLrh4CnfGYpC1FAd1BaIjSpryfQ5g7Cba3LoBgCzdNZO75KzzMTOybm6YQOt6AQf129yaoZwACfzyBYCsOPicEhyKJLgRCCoECZSuTP5YRCXgDjZudjQ6BA1iIpKZDiialVKt5qaM6DHaktCtzXgVteAK7N70wuMFtkJoRDHhpN8lOQgWdTxHQNAhCSDrWN9isxwak3mcEDVyv4+UuvyzK6iPKVJ3kPPE3DZ3H9jo2IQAh+QQFBQATACwAAAAAGgAaAAAFzmAkRsgAnEDwjGKJpuu4mOhgsNH82qxBvIIFzgcUjh6CnfGYrC0jhsDuMJTWqCzaSeDA6VBc74twYy2aJ7IXHWYdtID26F1T4BzwgZ2FByeGaHF/PWgEXXw/KIZ3iSdlIwqBAo8ikUA4CXmHI5k7mxEOgQNYI6FTPY0Ao0Opq6WiDHewbnACBTh0YLdztTG8QL4icGosDMOUEQxKOAV5TxHNNQg4SDvTLNUnPIQ7yAaFDV6pBOFmjQS7Iy6K6S1w5SMGefAi8js4DXnI+d0hACH5BAUFABMALAAAAAAaABoAAAXV4BONUoQMQAoEImmiajBG5QKngzHXN5C7BoIKIFjsIsFh0fUQDAdGplMFBQaeh6PhSs3ObErHEawSiEmLaYqgc6WH7GPPfDzMz7TI4ak4OnoDfS5/ZQlaakSGQGoEeCUOQiqNfpFEbXkKiAKXJZlUjhEJgKCiQ155DogDp4+qWpU+rEiwq4OqDH63LnZKBXVzvnm8ZS3Cc8URDD1xLspwnAWAUXnRT9MlqghHTU/aTE+cSKrhBowNY7AE526VBMF5J3DvJfE463kGgPcl+VThDYD+9QgBACH5BAUFABMALAAAAAAaABoAAAXUYPBM5BQhQwmIpYmqRhstKQkMcTnX0y0bBJVg8QvahrqHQDUgJpe2ps4QYB5+1eiVtBM6ZDSvbgHtEXJcsurcOvAAgq/OLda9BwqZ457XyXsCCT9lcIJTUAAEfyYORmaLEY1HaCYKhAKUEZZRkAl3nTwDW1wOhKJ6hKMmQFZFTKhMDLBRslx0RwUyt4C5tm8CI3O/wSYMb2w6xmtoEQV3TlzOTNATSkwIMtZR2DqmmQbeP2sNYI6J5GNGib1cLzYE7C41N+hcBnf1q/M4Mg13mf5KhAAAIfkEBQUAEwAsAAAAABoAGgAABdAgEDxTOUXIYIqkiarlYLjRAk+ATNvrQhuElcDnAgppD8FqQCxFkstmxBBYHn7VUu7q5GkFjt0NAHYtlFrCzIzGqV2HcRkuD5sc44GChl/uXW1kCT+BAoNFKwR2Tg5BaYsnjV9rTgqFlCeWWgOQEQl5nZ+bXIyBA6SRbac/jjirRa0ADHymsy4OpjRxQgW6cr1Ou18twXLEEQxjby7JiZQRBXlS0NIuUJsISKbZJgammFPfNLEEDTvk5maJwE4p6zTurulOBnnzJ/Wb4A15+zAhACH5BAUFABMALAAAAAAaABoAAAXQ4AQEz2ROETKcY3mmqzgYb7TEMv3ep7DUBgLLBxSaAL/XQ8AaJE2RZRMYaB6o1h0OIHDUeMfujnkk6KALssj8OmzF7bcX6tgOFLV6E38yqLkJQH8CgS9Ga3N0hwAEiSiJXGcoCoOSEZRHA44RCXabnZlXLw5/A6J0ZACmRVkvQScDDHmlsqN/BTVuQ7hxQ7lvLlC6YcERDFtsL8csySgFdk/O0EqlCDVSmdZQfk2W3JmSC4sEDV/j5S/IvFAqzOso2jLo23bzKAYxqpYNdvsrIQAh+QQFBQATACwAAAAAGgAaAAAFzSAgBk9kmsggjuUZpetguNGixrNrr8JCG4QVoPcLigY+10MgRNKWwsMv0JS6DNQYbcdzbG8igfe0YK4IObJZhHYdwMPx6S0UuxzwgYKGb+5PBmtDCT+CAoQnDkZsciaKQgSNEYZpJgqUNApNkgl5nGADVomCoXxrpVeLAKiAiwMMpk2wd2sCBTR0PLducC1zcAK+JrlhNAxwbS7HkJUFeUknzk3QEVAxCE+k2ICklRGBTZULqgQNW+TmJzBnu+rI7SZ56YDyP+E0DXne+SEAIfkEBQUAEwAsAAAAABoAGgAABc0gIALBE50nMoykiUbqOBhvtKwy/d6jsNQGAssHFIoGv9dDwELWlrIDMNCUvgzUkaPG6213OJGAyxwRdKhFWXR+HcIAwRf1Hs4jDvhAUcs3+SgGa3EJQIMChSgORmx3eIwABHcKh2gnlEOWEXqOCZw1CVV9gwNWimulRaJXjAMMo02vLw5rAgU1dT23bmECLnRwvrhwmgxwbS/GLAQ1BXpJKM5N0BFQMghPpNiBpJqCTZYLkAQNXOPlKDFmu+nH7BEGeuiB8jV6mg33NQ0hACH5BAUFABMALAAAAAAaABoAAAXN4ACMQPBEKIqIpJmqJDAYb7Sw41zfpLDUBkLMBxTmfq+HIDZAppSkwQEYYE5fhupI4NjhAFxvjPZaLEkEcsocI9QO3/ALPuymHN+BooZn7lMGZ1sJQIJghHdGIwR2iW2NEQqGAmookkOVCXmQEZpMnIZSfKFXd1ZFp1iKAwyjTK0vDoICBW9xtXM4Aie5Q7wpdIuVEQxfaTXFMU4oBXnLEc1MNVBRCNOh1oChw4FMlQuKAAQNO+HjLyttuCnpaOsRBnnkWPIvDXnD9941IQA7") !important;
}
```

* data 0: build failed;
* data 1: failed build in progress;
* data 2: build unstable;
* data 3: unstable build in progress;
* data 4: build stable;
* data 5: stable build in progress;
* data 13: first build of a project.
